### ISSUE TITLE
Add a delete option

### ISSUE THREAD

**Issue by Meyzerah** [laralove143/interchannel_message_mover#33]
Hi ! 

I'm fairly new user of your bot and first and foremore, I wanted to thank you for this feature ! It's so nice to manage our channels when we mess up, lol :D

I wanted to know if it's possible to add the option to delete or not the messages we move, because I want to do a smooth transition and deleting the moved messages is kinda harsh. :D

**Comment by laralove143** [comment]
does #12 cover your needs

**Comment by Meyzerah** [comment]
> thank youu, does #12 cover your needs

Sorry for the delaaaaay ! Duplicating the message in the new location and leaving  the old ones is fine for me, yes ! :D

**Comment by laralove143** [comment]
no problem, im closing this as duplicate of #12 then
